version: '3.8'

services:
  cyber_ctf_bot:
    build: .
    container_name: cyber_ctf_bot_24_7
    restart: always
    ports:
      - "2222:2222"
    env_file:
      - .env
    volumes:
      - ctf_data:/app/ctf_instances
      - db_data:/app/data

volumes:
  ctf_data:
  db_data:
